# Generated by Django 5.1.3 on 2024-12-31 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseparticipent',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzApp.participant'),
        ),
        migrations.AlterField(
            model_name='responseparticipent',
            name='question_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quizzApp.question'),
        ),
    ]
