# Generated by Django 5.1.3 on 2025-01-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzApp', '0002_alter_responseparticipent_participant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
