# Generated by Django 5.1.3 on 2025-01-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzApp', '0004_participant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='failed_quiz_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='passed_quiz_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='total_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='responseparticipent',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
