# Generated by Django 5.1.3 on 2025-01-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzApp', '0005_participant_failed_quiz_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('pakistan', 'Pakistan'), ('india', 'India'), ('bangladesh', 'Bangladesh')], default='pakistan', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=7),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('urdu', 'Urdu'), ('sindhi', 'Sindhi')], default='english', max_length=20),
        ),
    ]
